// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622062153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Models.Allergies", b =>
                {
                    b.Property<int>("AllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("allergy_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllergyId"));

                    b.Property<string>("Allergy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allergen");

                    b.HasKey("AllergyId");

                    b.ToTable("allergies");
                });

            modelBuilder.Entity("server.Models.Bunks", b =>
                {
                    b.Property<int>("BunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bunk_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BunkId"));

                    b.Property<string>("BunkName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bunk_name");

                    b.HasKey("BunkId");

                    b.ToTable("bunks");
                });

            modelBuilder.Entity("server.Models.Camper", b =>
                {
                    b.Property<int>("CamperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("camper_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CamperId"));

                    b.Property<int>("BunkId")
                        .HasColumnType("integer")
                        .HasColumnName("bunk_id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int>("GenderId")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("CamperId");

                    b.HasIndex("BunkId");

                    b.ToTable("campers");
                });

            modelBuilder.Entity("server.Models.CamperAllergies", b =>
                {
                    b.Property<int>("CamperAllergiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("camper_allergies_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CamperAllergiesId"));

                    b.Property<int>("AllergyId")
                        .HasColumnType("integer")
                        .HasColumnName("allergy_id");

                    b.Property<int>("CamperId")
                        .HasColumnType("integer")
                        .HasColumnName("camper_id");

                    b.HasKey("CamperAllergiesId");

                    b.HasIndex("AllergyId");

                    b.HasIndex("CamperId");

                    b.ToTable("camper_allergies");
                });

            modelBuilder.Entity("server.Models.CamperMedications", b =>
                {
                    b.Property<int>("CamperMedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("camper_medication_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CamperMedicationId"));

                    b.Property<int>("CamperId")
                        .HasColumnType("integer")
                        .HasColumnName("camper_id");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dosage");

                    b.Property<string>("DosageUnit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dosage_unit");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frequency");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<int>("MedicationId")
                        .HasColumnType("integer")
                        .HasColumnName("medication_id");

                    b.HasKey("CamperMedicationId");

                    b.HasIndex("CamperId");

                    b.HasIndex("MedicationId");

                    b.ToTable("camper_medications");
                });

            modelBuilder.Entity("server.Models.CamperParents", b =>
                {
                    b.Property<int>("CamperParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("camper_parent_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CamperParentId"));

                    b.Property<int>("CamperId")
                        .HasColumnType("integer")
                        .HasColumnName("camper_id");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.HasKey("CamperParentId");

                    b.ToTable("camper_parents");
                });

            modelBuilder.Entity("server.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gender_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenderId"));

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("GenderId");

                    b.ToTable("gender");
                });

            modelBuilder.Entity("server.Models.MedicationAdminLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("admin_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("AdministeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("admin_time");

                    b.Property<int>("CamperMedicationId")
                        .HasColumnType("integer")
                        .HasColumnName("camper_medication_id");

                    b.HasKey("LogId");

                    b.ToTable("medication_admin_log");
                });

            modelBuilder.Entity("server.Models.Medications", b =>
                {
                    b.Property<int>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("medication_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MedicationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medication_name");

                    b.HasKey("MedicationId");

                    b.ToTable("medications");
                });

            modelBuilder.Entity("server.Models.NursesPosts", b =>
                {
                    b.Property<int>("NursePostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NursePostId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("NurseMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nurse_message");

                    b.HasKey("NursePostId");

                    b.ToTable("nurse_posts");
                });

            modelBuilder.Entity("server.Models.Parent", b =>
                {
                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParentId"));

                    b.Property<string>("ParentFirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("ParentLastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("ParentId");

                    b.ToTable("parent");
                });

            modelBuilder.Entity("server.Models.Camper", b =>
                {
                    b.HasOne("server.Models.Bunks", "Bunk")
                        .WithMany()
                        .HasForeignKey("BunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bunk");
                });

            modelBuilder.Entity("server.Models.CamperAllergies", b =>
                {
                    b.HasOne("server.Models.Allergies", "Allergy")
                        .WithMany()
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Camper", "Camper")
                        .WithMany("CamperAllergies")
                        .HasForeignKey("CamperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Camper");
                });

            modelBuilder.Entity("server.Models.CamperMedications", b =>
                {
                    b.HasOne("server.Models.Camper", "Camper")
                        .WithMany()
                        .HasForeignKey("CamperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Medications", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camper");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("server.Models.Camper", b =>
                {
                    b.Navigation("CamperAllergies");
                });
#pragma warning restore 612, 618
        }
    }
}
